namespace QmkJson.Test
{
    internal static class InvalidJsons
    {
        public static bool Contains(string path)
        {
            // Undefined property
            if (path.EndsWith(@"cornia\info.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:91] |             "static_gradient": true, | The JSON property 'static_gradient' could not be mapped to any .NET member contained in type 'QmkJson.RgbMatrixAnimations'.
            if (path.EndsWith(@"stront\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:150] |         "led_count": 38, | The JSON property 'led_count' could not be mapped to any .NET member contained in type 'QmkJson.RgbMatrix'.
            if (path.EndsWith(@"1upkeyboards\super16v2\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:14] |         "animmations": { | The JSON property 'animmations' could not be mapped to any .NET member contained in type 'QmkJson.RgbMatrix'.
            if (path.EndsWith(@"1upkeyboards\sweet16v2\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:43] |         "animmations": { | The JSON property 'animmations' could not be mapped to any .NET member contained in type 'QmkJson.RgbMatrix'.
            if (path.EndsWith(@"ada\ada1800mini\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:137] |     ,"meta": "https://noroadsleft.github.io/kbf_qmk_converter/" | The JSON property 'meta' could not be mapped to any .NET member contained in type 'QmkJson.Keyboard'.
            if (path.EndsWith(@"ada\infinity81\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:145] |     ,"meta": "https://noroadsleft.github.io/kbf_qmk_converter/" | The JSON property 'meta' could not be mapped to any .NET member contained in type 'QmkJson.Keyboard'.
            if (path.EndsWith(@"binepad\knobx1\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:36] |             "gradient": true, | The JSON property 'gradient' could not be mapped to any .NET member contained in type 'QmkJson.RgblightAnimations'.
            if (path.EndsWith(@"boardsource\unicorne\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:19] |         "caps": "GP24" | The JSON property 'caps' could not be mapped to any .NET member contained in type 'QmkJson.Indicators'.
            if (path.EndsWith(@"bolsa\bolsalice\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:208] |     "meta": "https://noroadsleft.github.io/kbf_qmk_converter/" | The JSON property 'meta' could not be mapped to any .NET member contained in type 'QmkJson.Keyboard'.
            if (path.EndsWith(@"cipulot\ec_980c\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:41] |         "led_count": 3 | The JSON property 'led_count' could not be mapped to any .NET member contained in type 'QmkJson.RgbMatrix'.
            if (path.EndsWith(@"cipulot\ok_1\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:46] |             "fractal": true, | The JSON property 'fractal' could not be mapped to any .NET member contained in type 'QmkJson.RgbMatrixAnimations'.
            if (path.EndsWith(@"cmm_studio\fuji65\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:654] |     ,"meta": "https://noroadsleft.github.io/kbf_qmk_converter/" | The JSON property 'meta' could not be mapped to any .NET member contained in type 'QmkJson.Keyboard'.
            if (path.EndsWith(@"coban\pad12a\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:3] |     "name": "Coban Pad 12A", | The JSON property 'name' could not be mapped to any .NET member contained in type 'QmkJson.Keyboard'.
            if (path.EndsWith(@"coban\pad3a\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:3] |     "name": "Coban Pad 3A", | The JSON property 'name' could not be mapped to any .NET member contained in type 'QmkJson.Keyboard'.
            if (path.EndsWith(@"coban\pad9a\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:25] |     "name": "Coban Pad 9A", | The JSON property 'name' could not be mapped to any .NET member contained in type 'QmkJson.Keyboard'.
            if (path.EndsWith(@"custommk\evo70_r2\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:44] |             "rainbo_mood": true, | The JSON property 'rainbo_mood' could not be mapped to any .NET member contained in type 'QmkJson.RgblightAnimations'.
            if (path.EndsWith(@"eggsworks\egg58\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:37] |         "split": true, | The JSON property 'split' could not be mapped to any .NET member contained in type 'QmkJson.RgbMatrix'.
            if (path.EndsWith(@"eyeohdesigns\babyv\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:83] |         "led_count": 12, | The JSON property 'led_count' could not be mapped to any .NET member contained in type 'QmkJson.RgbMatrix'.
            if (path.EndsWith(@"ft\mars65\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:438] |   "meta": "https://noroadsleft.github.io/kbf_qmk_converter/" | The JSON property 'meta' could not be mapped to any .NET member contained in type 'QmkJson.Keyboard'.
            if (path.EndsWith(@"handwired\3dfoxc\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:104] |     "meta": "https://noroadsleft.github.io/kbf_qmk_converter/" | The JSON property 'meta' could not be mapped to any .NET member contained in type 'QmkJson.Keyboard'.
            if (path.EndsWith(@"handwired\cans12erv2\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:23] |     "host_language": "german", | The JSON property 'host_language' could not be mapped to any .NET member contained in type 'QmkJson.Keyboard'.
            if (path.EndsWith(@"handwired\carpolly\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:78] |     ,"meta": "https://noroadsleft.github.io/kbf_qmk_converter/" | The JSON property 'meta' could not be mapped to any .NET member contained in type 'QmkJson.Keyboard'.
            if (path.EndsWith(@"handwired\ibm_wheelwriter\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:110] |     ,"meta": "https://noroadsleft.github.io/kbf_qmk_converter/" | The JSON property 'meta' could not be mapped to any .NET member contained in type 'QmkJson.Keyboard'.
            if (path.EndsWith(@"handwired\oem_iso_fullsize\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:155] |     ,"meta": "https://noroadsleft.github.io/kbf_qmk_converter/" | The JSON property 'meta' could not be mapped to any .NET member contained in type 'QmkJson.Keyboard'.
            if (path.EndsWith(@"handwired\polly40\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:76] |     "meta": "https://noroadsleft.github.io/kbf_qmk_converter/" | The JSON property 'meta' could not be mapped to any .NET member contained in type 'QmkJson.Keyboard'.
            if (path.EndsWith(@"hnk\hnk100\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:51] |         "brightness_steps": 20, | The JSON property 'brightness_steps' could not be mapped to any .NET member contained in type 'QmkJson.RgbMatrix'.
            if (path.EndsWith(@"hnk\hnk65\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:51] |         "brightness_steps": 20, | The JSON property 'brightness_steps' could not be mapped to any .NET member contained in type 'QmkJson.RgbMatrix'.
            if (path.EndsWith(@"icebreaker\hotswap\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:50] |             "fractal": true, | The JSON property 'fractal' could not be mapped to any .NET member contained in type 'QmkJson.RgbMatrixAnimations'.
            if (path.EndsWith(@"keebmonkey\kbmg68\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:124] |     ,"meta": "https://noroadsleft.github.io/kbf_qmk_converter/" | The JSON property 'meta' could not be mapped to any .NET member contained in type 'QmkJson.Keyboard'.
            if (path.EndsWith(@"keenome_keys\the_grid_v2\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:24] |             "alpha_mods": true, | The JSON property 'alpha_mods' could not be mapped to any .NET member contained in type 'QmkJson.RgbMatrixAnimations'.
            if (path.EndsWith(@"keychron\q8\info.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:14] |         "wear_levling": { | The JSON property 'wear_levling' could not be mapped to any .NET member contained in type 'QmkJson.Eeprom'.
            if (path.EndsWith(@"kprepublic\bm43a\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:91] |     ,"meta": "https://noroadsleft.github.io/kbf_qmk_converter/" | The JSON property 'meta' could not be mapped to any .NET member contained in type 'QmkJson.Keyboard'.
            if (path.EndsWith(@"kprepublic\bm43hsrgb\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:97] |     ,"meta": "https://noroadsleft.github.io/kbf_qmk_converter/" | The JSON property 'meta' could not be mapped to any .NET member contained in type 'QmkJson.Keyboard'.
            if (path.EndsWith(@"kprepublic\bm980hsrgb\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:265] |     ,"meta": "https://noroadsleft.github.io/kbf_qmk_converter/" | The JSON property 'meta' could not be mapped to any .NET member contained in type 'QmkJson.Keyboard'.
            if (path.EndsWith(@"lz\erghost\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:397] |     ,"meta": "https://noroadsleft.github.io/kbf_qmk_converter/" | The JSON property 'meta' could not be mapped to any .NET member contained in type 'QmkJson.Keyboard'.
            if (path.EndsWith(@"mechlovin\infinity875\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:615] |     ,"meta": "https://noroadsleft.github.io/kbf_qmk_converter/" | The JSON property 'meta' could not be mapped to any .NET member contained in type 'QmkJson.Keyboard'.
            if (path.EndsWith(@"mechlovin\infinityce\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:371] |     ,"meta": "https://noroadsleft.github.io/kbf_qmk_converter/" | The JSON property 'meta' could not be mapped to any .NET member contained in type 'QmkJson.Keyboard'.
            if (path.EndsWith(@"mechlovin\kanu\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:359] |     ,"meta": "https://noroadsleft.github.io/kbf_qmk_converter/" | The JSON property 'meta' could not be mapped to any .NET member contained in type 'QmkJson.Keyboard'.
            if (path.EndsWith(@"mechlovin\th1800\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:156] |     ,"meta": "https://noroadsleft.github.io/kbf_qmk_converter/" | The JSON property 'meta' could not be mapped to any .NET member contained in type 'QmkJson.Keyboard'.
            if (path.EndsWith(@"mechlovin\tmkl\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:131] |     ,"meta": "https://noroadsleft.github.io/kbf_qmk_converter/" | The JSON property 'meta' could not be mapped to any .NET member contained in type 'QmkJson.Keyboard'.
            if (path.EndsWith(@"mechwild\bde\info.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:16] |         "tap_keycode_delay": 10, | The JSON property 'tap_keycode_delay' could not be mapped to any .NET member contained in type 'QmkJson.Tapping'.
            if (path.EndsWith(@"montsinger\rewind\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:2] |     "keyboard": "Rewind", | The JSON property 'keyboard' could not be mapped to any .NET member contained in type 'QmkJson.Keyboard'.
            if (path.EndsWith(@"nacly\bigsmoothknob\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:3] |     "name":"bigsmoothknob", | The JSON property 'name' could not be mapped to any .NET member contained in type 'QmkJson.Keyboard'.
            if (path.EndsWith(@"qwertyydox\rev1\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:4] |   "identifier": "0x1256", | The JSON property 'identifier' could not be mapped to any .NET member contained in type 'QmkJson.Keyboard'.
            if (path.EndsWith(@"sam\s80\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:146] |     ,"meta": "https://noroadsleft.github.io/kbf_qmk_converter/" | The JSON property 'meta' could not be mapped to any .NET member contained in type 'QmkJson.Keyboard'.
            if (path.EndsWith(@"skyloong\dt40\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:35] |             "dual_beacom": true, | The JSON property 'dual_beacom' could not be mapped to any .NET member contained in type 'QmkJson.RgbMatrixAnimations'.
            if (path.EndsWith(@"sowbug\68keys\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:232] |     ,"meta": "https://noroadsleft.github.io/kbf_qmk_converter/" | The JSON property 'meta' could not be mapped to any .NET member contained in type 'QmkJson.Keyboard'.
            if (path.EndsWith(@"sowbug\ansi_tkl\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:275] |     ,"meta": "https://noroadsleft.github.io/kbf_qmk_converter/" | The JSON property 'meta' could not be mapped to any .NET member contained in type 'QmkJson.Keyboard'.
            if (path.EndsWith(@"synthlabs\065\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:21] |             "alpha_mods": true, | The JSON property 'alpha_mods' could not be mapped to any .NET member contained in type 'QmkJson.RgbMatrixAnimations'.
            if (path.EndsWith(@"weirdo\tiger910\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:108] |     ,"meta": "https://noroadsleft.github.io/kbf_qmk_converter/" | The JSON property 'meta' could not be mapped to any .NET member contained in type 'QmkJson.Keyboard'.
            if (path.EndsWith(@"yandrstudio\transition80\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:21] |         "tap_capslock_delay": 10 | The JSON property 'tap_capslock_delay' could not be mapped to any .NET member contained in type 'QmkJson.Tapping'.
            if (path.EndsWith(@"zsa\moonlander\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:41] |     "mousekey": { | The JSON property 'mousekey' could not be mapped to any .NET member contained in type 'QmkJson.Keyboard'.
            if (path.EndsWith(@"zsa\planck_ez\info.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:28] |     "mousekey": { | The JSON property 'mousekey' could not be mapped to any .NET member contained in type 'QmkJson.Keyboard'.
            if (path.EndsWith(@"zsa\voyager\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:30] |     "mousekey": { | The JSON property 'mousekey' could not be mapped to any .NET member contained in type 'QmkJson.Keyboard'.
            if (path.EndsWith(@"acheron\apollo\87htsc\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:41] |             "fractal": true, | The JSON property 'fractal' could not be mapped to any .NET member contained in type 'QmkJson.RgbMatrixAnimations'.
            if (path.EndsWith(@"acheron\apollo\88htsc\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:41] |             "fractal": true, | The JSON property 'fractal' could not be mapped to any .NET member contained in type 'QmkJson.RgbMatrixAnimations'.
            if (path.EndsWith(@"gray_studio\think65\hotswap\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:134] |     ,"meta": "https://noroadsleft.github.io/kbf_qmk_converter/" | The JSON property 'meta' could not be mapped to any .NET member contained in type 'QmkJson.Keyboard'.
            if (path.EndsWith(@"gray_studio\think65\solder\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:283] |     ,"meta": "https://noroadsleft.github.io/kbf_qmk_converter/" | The JSON property 'meta' could not be mapped to any .NET member contained in type 'QmkJson.Keyboard'.
            if (path.EndsWith(@"handwired\tractyl_manuform\5x6_right\info.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:235] |         "led_count": 64, | The JSON property 'led_count' could not be mapped to any .NET member contained in type 'QmkJson.RgbMatrix'.
            if (path.EndsWith(@"input_club\infinity60\led\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:24] |             "solid_splash": true, | The JSON property 'solid_splash' could not be mapped to any .NET member contained in type 'QmkJson.LedMatrixAnimations'.
            if (path.EndsWith(@"keebio\sinc\rev4\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:83] |             "fractal": true, | The JSON property 'fractal' could not be mapped to any .NET member contained in type 'QmkJson.RgbMatrixAnimations'.
            if (path.EndsWith(@"keycapsss\kimiko\rev2\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:96] |         "led_count": 62, | The JSON property 'led_count' could not be mapped to any .NET member contained in type 'QmkJson.RgbMatrix'.
            if (path.EndsWith(@"keychron\x0\red\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:17] |             "solid_splash": true, | The JSON property 'solid_splash' could not be mapped to any .NET member contained in type 'QmkJson.LedMatrixAnimations'.
            if (path.EndsWith(@"mechlovin\hannah910\rev2\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:291] |     ,"meta": "https://noroadsleft.github.io/kbf_qmk_converter/" | The JSON property 'meta' could not be mapped to any .NET member contained in type 'QmkJson.Keyboard'.
            if (path.EndsWith(@"mechlovin\hannah910\rev3\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:212] |     ,"meta": "https://noroadsleft.github.io/kbf_qmk_converter/" | The JSON property 'meta' could not be mapped to any .NET member contained in type 'QmkJson.Keyboard'.
            if (path.EndsWith(@"mechlovin\olly\orion\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:374] |     "meta": "https://noroadsleft.github.io/kbf_qmk_converter/" | The JSON property 'meta' could not be mapped to any .NET member contained in type 'QmkJson.Keyboard'.
            if (path.EndsWith(@"montsinger\rebound\rev1\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:2] |     "keyboard": "Rebound Rev1", | The JSON property 'keyboard' could not be mapped to any .NET member contained in type 'QmkJson.Keyboard'.
            if (path.EndsWith(@"montsinger\rebound\rev2\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:2] |     "keyboard": "Rebound Rev2", | The JSON property 'keyboard' could not be mapped to any .NET member contained in type 'QmkJson.Keyboard'.
            if (path.EndsWith(@"montsinger\rebound\rev3\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:2] |     "keyboard": "Rebound Rev3", | The JSON property 'keyboard' could not be mapped to any .NET member contained in type 'QmkJson.Keyboard'.
            if (path.EndsWith(@"montsinger\rebound\rev4\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:2] |     "keyboard": "Rebound Rev4", | The JSON property 'keyboard' could not be mapped to any .NET member contained in type 'QmkJson.Keyboard'.
            if (path.EndsWith(@"sidderskb\majbritt\rev1\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:112] |     ,"meta": "https://noroadsleft.github.io/kbf_qmk_converter/" | The JSON property 'meta' could not be mapped to any .NET member contained in type 'QmkJson.Keyboard'.
            if (path.EndsWith(@"skyloong\qk21\v1\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:39] |             "dual_beacom": false, | The JSON property 'dual_beacom' could not be mapped to any .NET member contained in type 'QmkJson.RgbMatrixAnimations'.
            if (path.EndsWith(@"acheron\apollo\87h\delta\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:38] |             "fractal": true, | The JSON property 'fractal' could not be mapped to any .NET member contained in type 'QmkJson.RgbMatrixAnimations'.
            if (path.EndsWith(@"acheron\apollo\87h\gamma\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:38] |             "fractal": true, | The JSON property 'fractal' could not be mapped to any .NET member contained in type 'QmkJson.RgbMatrixAnimations'.
            if (path.EndsWith(@"handwired\bouvet\macropad\v1\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:16] |     "encoders": { | The JSON property 'encoders' could not be mapped to any .NET member contained in type 'QmkJson.Keyboard'.
            if (path.EndsWith(@"keychron\c1_pro\ansi\white\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:120] |             "solid_splash": true, | The JSON property 'solid_splash' could not be mapped to any .NET member contained in type 'QmkJson.LedMatrixAnimations'.
            if (path.EndsWith(@"keychron\c1_pro_v2\ansi\non_light\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:2] |     "keyboards_name": "Keychron C1 Pro V2 Non-Light", | The JSON property 'keyboards_name' could not be mapped to any .NET member contained in type 'QmkJson.Keyboard'.
            if (path.EndsWith(@"keychron\c1_pro_v2\ansi\white\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:17] |             "solid_splash": true, | The JSON property 'solid_splash' could not be mapped to any .NET member contained in type 'QmkJson.LedMatrixAnimations'.
            if (path.EndsWith(@"keychron\c2_pro\ansi\white\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:137] |             "solid_splash": true, | The JSON property 'solid_splash' could not be mapped to any .NET member contained in type 'QmkJson.LedMatrixAnimations'.
            if (path.EndsWith(@"keychron\c2_pro_v2\ansi\white\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:18] |             "solid_splash": true, | The JSON property 'solid_splash' could not be mapped to any .NET member contained in type 'QmkJson.LedMatrixAnimations'.
            if (path.EndsWith(@"keychron\c3_pro\ansi\red\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:22] |             "solid_splash": true, | The JSON property 'solid_splash' could not be mapped to any .NET member contained in type 'QmkJson.LedMatrixAnimations'.
            if (path.EndsWith(@"mechlovin\olly\jf\rev2\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:30] |             "solid_multisplash": true, | The JSON property 'solid_multisplash' could not be mapped to any .NET member contained in type 'QmkJson.LedMatrixAnimations'.

            // Missing comma
            if (path.EndsWith(@"doio\kb38\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:146] |                 {"matrix": [5, 7], "label": "KNOB_D", "x": 7.5, "y": 3.25, "w": 3, "h": 3} | '{' is invalid after a value. Expected either ',', '}', or ']'. Path: $.layouts.LAYOUT.layout[36] | LineNumber: 147 | BytePositionInLine: 16.
            if (path.EndsWith(@"dztech\dz60v2\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:59] |         "60_iso_tsangan_split_bs_rshift" | '"' is invalid after a value. Expected either ',', '}', or ']'. Path: $.community_layouts[11] | LineNumber: 59 | BytePositionInLine: 8.
            if (path.EndsWith(@"eason\aeroboard\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:49] |     "board": "STM32_F103_STM32DUINO" | '"' is invalid after a value. Expected either ',', '}', or ']'. Path: $ | LineNumber: 49 | BytePositionInLine: 4.
            if (path.EndsWith(@"eason\void65h\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:34] |     "community_layouts": ["65_ansi_blocker_tsangan", "65_ansi_blocker_tsangan_split_bs"] | '"' is invalid after a value. Expected either ',', '}', or ']'. Path: $ | LineNumber: 34 | BytePositionInLine: 4.
            if (path.EndsWith(@"handwired\ergo_v_1\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:111] |  | '{' is invalid after a value. Expected either ',', '}', or ']'. Path: $.layouts.LAYOUT.layout[63] | LineNumber: 112 | BytePositionInLine: 16.
            if (path.EndsWith(@"handwired\split_cloud\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:51] |         "protocol": "all" | '"' is invalid after a value. Expected either ',', '}', or ']'. Path: $ | LineNumber: 52 | BytePositionInLine: 4.
            if (path.EndsWith(@"keyten\lisa\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:19] |         "num_lock": "B11" | '"' is invalid after a value. Expected either ',', '}', or ']'. Path: $ | LineNumber: 20 | BytePositionInLine: 4.
            if (path.EndsWith(@"montsinger\palmetto\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:32] |         "60_iso_tsangan_split_bs_rshift" | '"' is invalid after a value. Expected either ',', '}', or ']'. Path: $.community_layouts[8] | LineNumber: 32 | BytePositionInLine: 8.
            if (path.EndsWith(@"mwstudio\mmk_3\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:39] |     "ws2812": { | '"' is invalid after a value. Expected either ',', '}', or ']'. Path: $.ws2812 | LineNumber: 40 | BytePositionInLine: 8.
            if (path.EndsWith(@"themadnoodle\noodlepad_micro\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:62] |         "rotary": [ | '{' is invalid after a value. Expected either ',', '}', or ']'. Path: $.encoder.rotary[1] | LineNumber: 63 | BytePositionInLine: 12.
            if (path.EndsWith(@"enviousdesign\commissions\mini1800\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:21] |     } | '"' is invalid after a value. Expected either ',', '}', or ']'. Path: $ | LineNumber: 21 | BytePositionInLine: 4.
            if (path.EndsWith(@"era\linx3\n8x\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:1135] |             ] | '"' is invalid after a value. Expected either ',', '}', or ']'. Path: $.layouts.LAYOUT_tkl_iso_wkl | LineNumber: 1136 | BytePositionInLine: 8.
            if (path.EndsWith(@"handwired\scottokeebs\scottoinvader\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:16] |  | '"' is invalid after a value. Expected either ',', '}', or ']'. Path: $.matrix_pins | LineNumber: 17 | BytePositionInLine: 8.
            if (path.EndsWith(@"kprepublic\bm40hsrgb\rev1\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:113] |             {"x": 0, "y": 32, "flags": 2} | '"' is invalid after a value. Expected either ',', '}', or ']'. Path: $.rgb_matrix | LineNumber: 114 | BytePositionInLine: 8.
            if (path.EndsWith(@"kprepublic\bm60hsrgb\rev1\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:129] |             {"x": 36, "y": 32, "flags": 2} | '"' is invalid after a value. Expected either ',', '}', or ']'. Path: $.rgb_matrix | LineNumber: 130 | BytePositionInLine: 8.
            if (path.EndsWith(@"kprepublic\bm60hsrgb_ec\rev1\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:123] |             {"x": 36, "y": 32, "flags": 2} | '"' is invalid after a value. Expected either ',', '}', or ']'. Path: $.rgb_matrix | LineNumber: 124 | BytePositionInLine: 8.
            if (path.EndsWith(@"kprepublic\bm60hsrgb_ec\rev2\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:102] |             {"matrix": [4, 13], "x": 224, "y": 64, "flags": 1} | '"' is invalid after a value. Expected either ',', '}', or ']'. Path: $.rgb_matrix | LineNumber: 103 | BytePositionInLine: 8.
            if (path.EndsWith(@"kprepublic\bm60hsrgb_iso\rev1\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:130] |             {"x": 36, "y": 32, "flags": 2} | '"' is invalid after a value. Expected either ',', '}', or ']'. Path: $.rgb_matrix | LineNumber: 131 | BytePositionInLine: 8.
            if (path.EndsWith(@"kprepublic\bm60hsrgb_poker\rev1\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:126] |             {"x": 36, "y": 32, "flags": 2} | '"' is invalid after a value. Expected either ',', '}', or ']'. Path: $.rgb_matrix | LineNumber: 127 | BytePositionInLine: 8.
            if (path.EndsWith(@"kprepublic\bm65hsrgb_iso\rev1\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:159] |             {"x": 36, "y": 32, "flags": 2} | '"' is invalid after a value. Expected either ',', '}', or ']'. Path: $.rgb_matrix | LineNumber: 160 | BytePositionInLine: 8.
            if (path.EndsWith(@"kprepublic\bm68hsrgb\rev1\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:134] |             {"x": 25, "y": 45, "flags": 2} | '"' is invalid after a value. Expected either ',', '}', or ']'. Path: $.rgb_matrix | LineNumber: 135 | BytePositionInLine: 8.
            if (path.EndsWith(@"mechboards\sofle\pro\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:97] |             {"matrix": [8, 5], "x": 144, "y": 47, "flags": 4} | '{' is invalid after a value. Expected either ',', '}', or ']'. Path: $.rgb_matrix.layout[63] | LineNumber: 97 | BytePositionInLine: 12.
            if (path.EndsWith(@"phdesign\ph60\multi\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:30] |     "community_layouts": ["60_ansi", "60_ansi_tsangan_split_bs_rshift", "60_iso"] | '"' is invalid after a value. Expected either ',', '}', or ']'. Path: $ | LineNumber: 30 | BytePositionInLine: 4.
            if (path.EndsWith(@"smithrune\magnus\m75s\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:51] |         } | '"' is invalid after a value. Expected either ',', '}', or ']'. Path: $ | LineNumber: 52 | BytePositionInLine: 4.
            if (path.EndsWith(@"keychron\s1\ansi\rgb\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:120] |             {"matrix": [5, 14], "x": 224, "y": 64, "flags": 1} | '"' is invalid after a value. Expected either ',', '}', or ']'. Path: $.rgb_matrix | LineNumber: 121 | BytePositionInLine: 8.

            // Invalid escaping
            if (path.EndsWith(@"acheron\themis\87h\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:115] |                 {"label":"\'\"", "matrix": [3, 11], "x": 11.75, "y": 3.25}, | ''' is an invalid escapable character within a JSON string. The string should be correctly escaped. Path: $ | LineNumber: 114 | BytePositionInLine: 27.
            if (path.EndsWith(@"acheron\themis\87htsc\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:115] |                 {"label":"\'\"", "matrix": [3, 11], "x": 11.75, "y": 3.25}, | ''' is an invalid escapable character within a JSON string. The string should be correctly escaped. Path: $ | LineNumber: 114 | BytePositionInLine: 27.
            if (path.EndsWith(@"acheron\themis\88htsc\keyboard.json", StringComparison.OrdinalIgnoreCase)) return true; // [LineNumber:117] |                 {"label":"\'\"", "matrix": [3, 11], "x": 11.75, "y": 3.25}, | ''' is an invalid escapable character within a JSON string. The string should be correctly escaped. Path: $ | LineNumber: 116 | BytePositionInLine: 27.

            return false;
        }
    }
}
